### ISSUE TITLE
Its Not ordering as intended

### ISSUE THREAD

**Issue by FerchoCarcho** [jarektkaczyk/eloquence#121]
Hello @jarektkaczyk 
Im using Eloquence along a <  table  >, so when I dont search for anything and Order the title from A-Z
it obviously does it correctly.
But when I filter the table with:
```
$rq= Post::search($q)->orderBy($sortkey, $order)->paginate(8);
```
It gives me the 3 first posts unordered and beginning with the fourth the order is correct from A-Z.
I had modified the weights of 
```
protected $searchableColumns = [
        'title'=>0,
        'body'=>1
    ];
```
and now it works, but.... When I give the sort order of $sortkey=published, it breaks again and it orders incorrectly.
In my table I have multiple sortKeys, I wont like to play with weights with every Th to make the filter works. Because I would have N posibilities. Is there a way to make it work straightforward.?

**Comment by stephendj** [comment]
+1

**Comment by jarektkaczyk** [comment]
@FerchoCarcho searchable is about returning results ordered *by relevance*. It makes no sense to use different order than that. If all you want to do is *filter* by your search query, then you can manually join the relations (using `RelationJoiner`) and building the `wheres` directly, without need for the heavy subquery that is otherwise required for the relevance score.
