### ISSUE TITLE
Fulltext search with Searchable

### ISSUE THREAD

**Issue by kfirba** [jarektkaczyk/eloquence#13]
Hello.

I've been looking at the package and I just realised that no-where in the documentation there is a requirement that we need to add a fulltext index to the columns we want to search.

Am I missing something?

**Comment by jarektkaczyk** [comment]
It doesn't use `fulltext` search (`match .. against` clause). It mimics fulltext in basic way and handles the search with `joins` and `where .. like` clauses. Otherwise it wuldn't be possible to join anything just like that.

**Comment by kfirba** [comment]
@jarektkaczyk And how is it in terms of speed compared to fulltext? or actually compared to any search type?

**Comment by jarektkaczyk** [comment]
I didn't run any benchmarks :) It is definitely not suitable for any kind of big data, because it could get unbearably slow. Other than that, it should be just fine.

If you expect or experience during utilization of the `searchable` low performance, then I suggest switching to dedicated solution, like elastic and such stuff. This one is rather very simple `plug&play` search functionality, but should be enough for many use-cases.

**Comment by kfirba** [comment]
@jarektkaczyk I see. Thanks a lot!

**Comment by Mevrael** [comment]
Yeah, this one does not uses fulltext indexes...

@kfirba did you found any solution using real fulltext search?
