### ISSUE TITLE
Sofa\Eloquence\Contracts\Metable not used?

### ISSUE THREAD

**Issue by lukasoppermann** [jarektkaczyk/eloquence#133]
Hey @jarektkaczyk it seems this contract is not used at all. Why is this? Is this correct?

```
Sofa\Eloquence\Contracts\Metable
```

**Comment by jarektkaczyk** [comment]
Hey Lucas, can't check now, but I guess I just leaned towards simplicity
thus the interface that simply supported a trait might not be in use
anymore.

Jarek Tkaczyk

softonsofa :: development with pleasure

On Nov 2, 2016 01:54, "Lukas Oppermann" <notifications@github.com> wrote:

Hey @jarektkaczyk <https://github.com/jarektkaczyk> it seems this contract
is not used at all. Why is this? Is this correct?

Sofa\Eloquence\Contracts\Metable

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jarektkaczyk/eloquence/issues/133>, or mute the thread
