### ISSUE TITLE
Support for Laravel 5.5

### ISSUE THREAD

**Issue by matthbon** [jarektkaczyk/eloquence#194]
Any idea when support for Laravel 5.5 will be available?

Thanks.

**Comment by gtapps** [comment]
Yes Laravel 5.5 support would be great. I've already started the migration but a few things are required to be tweaked in order to work with Laravel 5.5 such as getCountForPagination way of working seems to have changed.

**Comment by mrjohnmain** [comment]
+1

**Comment by rhoseno98** [comment]
+1

**Comment by LaurentEsc** [comment]
+1

**Comment by NikolasMatias** [comment]
+1

**Comment by chrisgo** [comment]
+1

**Comment by pardavib** [comment]
+1

**Comment by carlospalacin** [comment]
+1

**Comment by itsjavi** [comment]
This is a duplicated ticket.
Please check this merge request, maybe you can contribute with it or review it / test it to get it ready
https://github.com/jarektkaczyk/eloquence/pull/195

**Comment by ragingdave** [comment]
Considering that @gtapps  backed out of updating to L5.5.....is there anyone is handling that @jarektkaczyk or anyone else? I would offer up some time myself if it would help but I don't know if I have enough domain knowledge about this and hookable to update it

**Comment by amirulahmad** [comment]
+1

**Comment by jarektkaczyk** [comment]
Laravel doesn't give a shit about any backward compatibility with anything, so updates are time consuming and a bit tedious. 
Right now I am overloaded with my work, so cannot do that, but will gladly review and merge a PR when somebody does it.

**Comment by SirLamer** [comment]
Just a thought, I think maintenance of this package would benefit a lot from separation of its main features in to separate packages. This is a collection of separate things mixed in together which makes it hard to navigate. Also, there will be a lot of people who just want to make use of one feature, like just the validation feature, or just the searching feature.

**Comment by jarektkaczyk** [comment]
@SirLamer ok, will look into it. thanks for suggestion

**Comment by mrjohnmain** [comment]
@SirLamer Agreed! Personally it's the subqueries that I make most use of :)

**Comment by Marvellanius** [comment]
+1

**Comment by ragingdave** [comment]
Not trying to push, but given that 5.5 has already been released.....and at least from the outside looking in (could totally be wrong) there's been no movement on this. Is there any timeframe for 5.5 compatibility from either perspective of splitting the repos or just upgrading this repo?

**Comment by SirLamer** [comment]
I don't want to trash this package too much, but in the spirit of helping people upgrade to 5.5... I have chosen to abandon relying on this package, because it is not really receiving development support anymore. That is okay, I understand real life takes priority and all that, so rather than prod I have decided to control my destiny.

To that end, I have found and implemented a collection of other packages which implement the features I was using from Eloquent in a similar way. I am sharing these just in the spirit of helping those who are looking for 5.5 compatibility, and not to slam on Eloquence. Peace and love.
- For ranked/sorted search results: https://github.com/nicolaslopezj/searchable (The Eloquence search feature is actually based on this package)
- For in-model validation: https://github.com/dwightwatson/validating
- For table column sorting https://github.com/Kyslik/column-sortable (not a direct feature of Eloquence however one of the implied uses of Mappable is easy orderBy calls, this pack has a similar result)

**Comment by jarektkaczyk** [comment]
Tagged 5.5. 
Feel free to use other packages if that helps with your work.

However, the biggest benefit you can get is actually by participating in the development and maintenance - there's not much value for a dev in wiring packages only, unless you don't want to broaden your mind and develop your skill, but rather this is ONLY how you make a living.

happy coding! :surfing_man: :surfing_woman:

**Comment by SirLamer** [comment]
I totally agree, that's why I suggest bundling all these features in to one fun package has a cost.  If you look at the three packages I listed, you will see that I submitted and had adopted multiple PR requests to them. With this one, I don't know where to start. I think that's why this one particular package in particular gets much less community support than others, despite the collective functional offering being excellent.

**Comment by jarektkaczyk** [comment]
@SirLamer So I asked my kids whether they would be OK if I spend some time on eloquence, rather than reading them stories and they agreed :yum: 

That being said I've done a quick review and extracted what could be easily separated:

[Base & Searchable](https://github.com/jarektkaczyk/eloquence-base)
[Validable](https://github.com/jarektkaczyk/eloquence-validable)
[Mappable](https://github.com/jarektkaczyk/eloquence-mappable)
[Metable](https://github.com/jarektkaczyk/eloquence-metable)
[Mutable](https://github.com/jarektkaczyk/eloquence-mutable)


This particular package remains as one to rule them all, without BC breaking change, so it continues on `v5.5.x`.


cheers!
