### ISSUE TITLE
Search on columns from a joined table?

### ISSUE THREAD

**Issue by docmattman** [jarektkaczyk/eloquence#57]
I'm using a table join, but can't figure out how to search on a column from the joined table.  I know that I can use columns from a table with a relationship, but can I do it on a straight joined table?

Here is what I'm trying:

```
User::leftJoin('users_profiles', 'users_profiles.user_id', '=', 'profile.id')
->search($string, ['username' => 10, 'users_profiles.email' => 20, 'users_profiles.firstname' => 5])
->get();
```

Gives an error:

```
Fatal error: Uncaught exception 'BadMethodCallException' with message 'Call to undefined method Sofa\Eloquence\Query\Builder::users_profiles()' in /vendor/illuminate/database/Query/Builder.php:2161
```

Any idea how I can search joined tables without creating relationships in the model instead?

**Comment by jarektkaczyk** [comment]
@docmattman Currently it's not possible to search on the manually joined tables - you need to create appropriate relation in order to do so.

The search is processed on the subquery, while your join is made on the outer query, that's why it can't work, even if we change the behaviour of how the search mappings are handled.
