### ISSUE TITLE
Eloquent OrderBy() not working after call to eloquence search method

### ISSUE THREAD

**Issue by ooiginla** [jarektkaczyk/eloquence#94]
When i used the search() method ordinarily, it works fine based on the field $searchableColumns.
But when i combine it with eloquent method orderBy('title','asc') ....the result is not sorted by the column i want which is not part of the fields i am using to search.

`// result is not sorted by title.
$product =  $product->search($keywords)->orderBy('title','desc')->get();
`

**Comment by SirLamer** [comment]
That is happening because Eloquence assigns weighting inside the SQL query and the uses 'ORDER BY' in order to sort the results using the SQL server. When you then add your own "->orderBy()", yours get appended after the weighting.

I have this issue in some contexts (sortable columns in a table interface). This is crude, but you can scrub the orderBy out of the query after Eloquence adds it to the stack but before the SQL is generated.

>            $query= product->search($keywords);
            $subquery = $query->getQuery();
            $subquery->orders = [];
            $query->setQuery($subquery);
            $product = $query->orderBy('title', 'desc')->get();

Keep in mind that Eloquence is running much more complex SQL queries for the sake of weighted results, so they take longer to execute, then the above trick nullifies the value of this. So, as is the case for me, this might work when you want the first result in a tabulated view of data produced by a search query to be presented on a weighted basis, but then allow the user to apply a column sort and refresh without having two separate query methods in your code.

**Comment by jarektkaczyk** [comment]
Agree with SirLamer - sorting by anything else but relevance score ruins the idea of whole searchable feature.
